### ISSUE TITLE
problem of "one to one relation" and "muti unique index"

### ISSUE THREAD

**Issue by Zuckonit** [PiTiLeZarD/workbench_alchemy#2]
>    firstly, thank you for this great tool, which save so much time of mine.
>    during my work, I found some problem about this tool:
> - 1. one to one relation, why not use:  
>      `uselist = False`
> - 1. multi unique index, this is inactive by using UniqueConstraint (mybe in some special sqlalchemy version or mysql version)  
>   
>   ```
>   UniqueConstraint('assailant_id', 'sample_id', 'sample_type', name='assailant_sample_uqe')
>   ```
>   
>   instead below is active:  
>   
>   ```
>       __table_args__ = ({'mysql_engine': 'InnoDB', 'sqlite_autoincrement': True, 'mysql_charset': 'utf8'}
>   , UniqueConstraint('assailant_id', 'sample_id', 'sample_type', name='assailant_sample_uqe'))
>   ```

**Comment by PiTiLeZarD** [comment]
Yeah you've probably given up, but I just added options for uselist, it's not automatic yet, I might look into that soon
