### ISSUE TITLE
Primary key column renamed and aliased

### ISSUE THREAD

**Issue by mbo42** [PiTiLeZarD/workbench_alchemy#5]
When exporting this table from the database ...

CREATE TABLE IF NOT EXISTS `ass_register`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB

I get the idperson column renamed like so:

class Person(DECLARATIVE_BASE):

```
__tablename__ = 'person'
__table_args__ = (
    {'mysql_engine': 'InnoDB', 'sqlite_autoincrement': True, 'mysql_charset': 'utf8'}
)

id = Column(  # pylint: disable=invalid-name
    "idperson", INTEGER, autoincrement=True, primary_key=True, nullable=False
)
lastname = Column(VARCHAR(45))
firstname = Column(VARCHAR(45))

def __repr__(self):
    return self.__str__()

def __str__(self):
    return "<Person(%(id)s)>" % self.__dict__
```

As Professor Julius would say "Why is it so?"
P.S. Wonderful tool !

**Comment by PiTiLeZarD** [comment]
Hey there,

So if I got that right, you're wondering why is there an auto alias on all
primary columns in case of single primary columns tables?

I did this as a taste thing. I have no real explanation for it, but look at
it this way:
All your objects will then have an attribute "id" which refers to whatever
the column is, you can then have generic scripts that don't have to build
id names on the fly.

It's like having a name convention for date_created, date_updated,
date_modified or something.

I'm not sure about how I did this (I should really refresh it to be honest)
but you might be able to change the name of the id using an
alias="id_whatever" in the comment of that column.

Or you can fiddle around and remove the auto id alias from the code
directly ;)

Thanks for the interest! I hope I answered your question?

Cheers

--
Jonathan Adami
Infrastructure Specialist - Python/Javascript Developer

**Comment by mbo42** [comment]
Ok. I haven't really worked out why yet, but the alias won't work in my code ...
`AttributeError: type object 'Person' has no attribute 'idperson'`

I usually just edit that class.
I did look for how to kill it it the script, but haven't found it yet ... I'll keep looking.

While I've got you ... Have you ever considered supporting SQLite cascade deletes ?

**Comment by PiTiLeZarD** [comment]
I thought about so many things doing this tool! But I mainly did it while
doing another project, so everything I implemented everything I was using
at the time...

It's been a while I didn't use it, so I might come back to it eventually!

About the alias you have to use the comments in the workbench, the script
will read those comments and use it while generating the code.

Hope it helped!

--
Jonathan Adami
Infrastructure Specialist - Python/Javascript Developer

**Comment by mbo42** [comment]
It helped, Thanks!

**Comment by mbo42** [comment]
Hey, I've added (hacked in...?) a relationship option for 'uselist=False', needed for one-to-one. This uses the longer version of backref - backref=backref("fieldname", uselist=False). Interested?
Also, where do think would be a good place to put an option for the id aliasing?

**Comment by PiTiLeZarD** [comment]
@mbo42 Good stuff with the uselist, I'll add it now (yes after that long I'm finally reviving this project ;)) I'll also think of a way to disable the id aliasing. I find it convenient though, to know every object has an id. But I'll look into it.
