### ISSUE TITLE
column default values produce invalid python code

### ISSUE THREAD

**Issue by runout-at** [PiTiLeZarD/workbench_alchemy#6]
Hi! Thx for that tool.
If i have in the MySQL create table following column definition:
`mod_timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`

I get following after running the script and python claims that this is invalid syntax:
`mod_timestamp = Column(TIMESTAMP, default=CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`

any idias how to fix this?

**Comment by PiTiLeZarD** [comment]
I know I'm super late to the party here but this should be fixed :D
https://github.com/PiTiLeZarD/workbench_alchemy/blob/master/tests.py#L157

I didn't need that tool for a while, and I really thought that someone would take over. So here I am trying to fix it up, tell me if there's anything else.
